### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by tuxiano** [prof-membrane/plugin.video.3satmediathek#3]
Hi, 

vielen Dank für die super Plugins. Leider funktioniert das 3sat Plugin (Version 1.3, Libreelec 9.0.2, RPi3b+) nicht mehr:

```
2019-06-11 21:16:25.046 T:1237652336 WARNING: Repository add-on repository.membrane uses plain HTTP for add-on downloads in path http://github.com/prof-membrane/repository.membrane/raw/master/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2019-06-11 21:16:39.106 T:1341301616 WARNING: Previous line repeats 2 times.
2019-06-11 21:16:39.107 T:1341301616 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
2019-06-11 21:16:39.107 T:1341301616 WARNING: Previous line repeats 1 times.
2019-06-11 21:16:39.107 T:1341301616  NOTICE: LoadJpeg: unable to load /storage/.kodi/addons/plugin.video.3satmediathek/fanart.jpg
2019-06-11 21:16:41.046 T:1937330192   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-06-11 21:16:43.386 T:1313186672   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.3satmediathek/default.py", line 4, in <module>
                                                list()
                                              File "/storage/.kodi/addons/script.module.lib3sat/lib/lib3sat.py", line 83, in list
                                                l = modes.get(mode)()
                                              File "/storage/.kodi/addons/script.module.lib3sat/lib/lib3sat.py", line 27, in lib3satListNew
                                                return xmlservice.getNew(baseXml,modePrefix)
                                              File "/storage/.kodi/addons/script.module.mediathekxmlservice/lib/mediathekxmlservice.py", line 9, in getNew
                                                return listing.getXML(baseUrl+'/xmlservice/web/aktuellste?maxLength=50&id=%5FSTARTSEITE',modePrefix)
                                              File "/storage/.kodi/addons/script.module.mediathekxmlservice/lib/mediathekxmlservicelisting.py", line 14, in getXML
                                                response = libMediathek.getUrl(url)
                                              File "/storage/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 34, in getUrl
                                                return _request(url,headers,post,cookies)
                                              File "/storage/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 82, in _request
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 467, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
2019-06-11 21:16:43.410 T:1409061744   ERROR: GetDirectory - Error getting plugin://plugin.video.3satmediathek/?mode=lib3satListNew&name=Neu
2019-06-11 21:16:43.411 T:1937330192   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.3satmediathek/?mode=lib3satListNew&name=Neu) failed
2019-06-11 21:16:45.947 T:1237652336 WARNING: Repository add-on repository.membrane uses plain HTTP for add-on downloads in path http://github.com/prof-membrane/repository.membrane/raw/master/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2019-06-11 21:18:01.824 T:1937330192 WARNING: Previous line repeats 2 times.
2019-06-11 21:18:01.824 T:1937330192  NOTICE: Samba is idle. Closing the remaining connections

################################################################################
# ... output of cat /storage/.kodi/temp/kodi.old.log
# LibreELEC release: RPi2.arm-9.0.2
```

Wäre super, wenn du den Fehler beheben könntest.

Vielen Dank.

**Comment by jaylinski** [comment]
das GitHub profil des autors hat seit über einem jahr keine aktivität mehr. Ich werd mal versuchen das zu fixen.

**Comment by tuxiano** [comment]
> das GitHub profil des autors hat seit über einem jahr keine aktivität mehr. Ich werd mal versuchen das zu fixen.

Danke, dass ist sehr nett.

**Comment by dmark04** [comment]
Irgendwelche Neuigkeiten zu diesem Problem?

**Comment by jaylinski** [comment]
Ich glaub da passiert nicht mehr viel.

@sarbes hat allerdings das plugin geforked (https://github.com/sarbes/plugin.video.3satmediathek) und im matrix branch gepublished (https://github.com/xbmc/repo-plugins/pull/2855)
